# ==========================================
# PARÀMETRES GLOBALS
# ==========================================
authoritative;
one-lease-per-client on;
default-lease-time 600;
max-lease-time 7200;
option domain-name "aula53.asir";
option domain-name-servers 192.168.1.10, 192.168.1.11;

# ==========================================
# PARÀMETRES DE SEGURETAT
# ==========================================
ddns-update-style none;
deny declines;
deny bootp;

# ==========================================
# DEFINICIÓ DE SUBXARXA I RANG DINÀMIC
# ==========================================
subnet 192.168.1.0 netmask 255.255.255.0 {
    range 192.168.1.100 192.168.1.200;
    option broadcast-address 192.168.1.255;
    option routers 192.168.1.1;
    option subnet-mask 255.255.255.0;
}

# ==========================================
# RESERVES PER ADREÇA FÍSICA (MAC)
# ==========================================
host Isabel {
    hardware ethernet 00:00:45:12:EE:F4;
    fixed-address 192.168.1.21;
    default-lease-time -1;
    max-lease-time -1;
    option host-name "Isabel";
}

host Fernando {
    hardware ethernet 00:00:45:13:1E:44;
    fixed-address 192.168.1.22;
    option domain-name-servers 192.168.1.20;
}
